// Autonomy Layer Type Definitions
// Generated by Scaffold Agent for SAW Wave (autonomy-web-ui)
// These types mirror the backend autonomy layer (v0.58.0) from scout-and-wave-go

// Autonomy level type — mirrors pkg/autonomy.Level
export type AutonomyLevel = 'gated' | 'supervised' | 'autonomous'

// Autonomy config — mirrors pkg/autonomy.Config
export interface AutonomyConfig {
  level: AutonomyLevel
  max_auto_retries: number
  max_queue_depth: number
}

// Queue item — mirrors pkg/queue.Item
export interface QueueItem {
  title: string
  priority: number
  depends_on?: string[]
  feature_description: string
  status: 'queued' | 'in_progress' | 'complete' | 'blocked'
  autonomy_override?: string
  require_review?: boolean
  slug?: string
  file_path?: string
}

// Daemon state — mirrors pkg/engine.DaemonState
export interface DaemonState {
  running: boolean
  current_impl?: string
  current_wave?: number
  queue_depth: number
  completed_count: number
  blocked_count: number
}

// Pipeline entry — combined view of completed + executing + queued
export interface PipelineEntry {
  slug: string
  title: string
  status: 'complete' | 'executing' | 'blocked' | 'queued'
  wave_progress?: string        // e.g. "Wave 2/3"
  active_agent?: string         // e.g. "Agent B"
  blocked_reason?: string
  queue_position?: number
  depends_on?: string[]
  completed_at?: string
  elapsed_seconds?: number
}

// Pipeline response from GET /api/pipeline
export interface PipelineResponse {
  entries: PipelineEntry[]
  metrics: PipelineMetrics
  autonomy_level: AutonomyLevel
}

// Throughput metrics
export interface PipelineMetrics {
  impls_per_hour: number
  avg_wave_seconds: number
  queue_depth: number
  blocked_count: number
  completed_count: number
}

// Add queue item request
export interface AddQueueItemRequest {
  title: string
  priority: number
  feature_description: string
  depends_on?: string[]
  autonomy_override?: string
  require_review?: boolean
}
